// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRAmJB3kqpQJ5nuk0oA82voaukemuhauQ',
    appId: '1:1046231516159:web:15c45e59c3802d35d91dca',
    messagingSenderId: '1046231516159',
    projectId: 'taalim-f3f0d',
    authDomain: 'taalim-f3f0d.firebaseapp.com',
    storageBucket: 'taalim-f3f0d.appspot.com',
    measurementId: 'G-XQGSSSSJG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVCWNfE0YjfEoBJ4fkTEwEOGgh3Hw2qM',
    appId: '1:1046231516159:android:3a3b3d7a3c8f9bffd91dca',
    messagingSenderId: '1046231516159',
    projectId: 'taalim-f3f0d',
    storageBucket: 'taalim-f3f0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAI_eg5BdJh7GQawvb3vEf0WiUMn29g3s',
    appId: '1:1046231516159:ios:b38967adc9a2e182d91dca',
    messagingSenderId: '1046231516159',
    projectId: 'taalim-f3f0d',
    storageBucket: 'taalim-f3f0d.appspot.com',
    iosBundleId: 'com.example.taalim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAI_eg5BdJh7GQawvb3vEf0WiUMn29g3s',
    appId: '1:1046231516159:ios:b38967adc9a2e182d91dca',
    messagingSenderId: '1046231516159',
    projectId: 'taalim-f3f0d',
    storageBucket: 'taalim-f3f0d.appspot.com',
    iosBundleId: 'com.example.taalim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRAmJB3kqpQJ5nuk0oA82voaukemuhauQ',
    appId: '1:1046231516159:web:ba657d0df7ab0f67d91dca',
    messagingSenderId: '1046231516159',
    projectId: 'taalim-f3f0d',
    authDomain: 'taalim-f3f0d.firebaseapp.com',
    storageBucket: 'taalim-f3f0d.appspot.com',
    measurementId: 'G-M492EN9D1B',
  );
}
